### ISSUE TITLE
Proposal: Follow GitHub's Roadmap Structure & Rename This Repo to `cdp-roadmap`

### ISSUE THREAD

**Issue by hawkticehurst** [CouncilDataProject/long-term-eng#12]
As we start to look towards post v3 work I think it would be cool/helpful to centralize all of our long-term work into one place and wouldn't ya know it we already have a repo that's already doing some of this job! 😉

I propose that we take this repo even further and follow the structure/model that GitHub does for its public roadmap:

[https://github.com/github/roadmap](https://github.com/github/roadmap)

Like us, GitHub also uses Issue tracking to collect ideas for long-term goals. However, it notably takes the planning further by using the "Projects" tab board feature (which will be updated soon to also include even more [project planning features](https://github.com/features/issues)) to track features on a long term scale. @sarahjliu this is could be a really nice place to centralize CDP-wide goals/objectives.

The repo also takes advantage of the README by including a high-level summary of the various features that are in the pipeline so those curious about GitHub's future don't have to deeply dive into the Projects/Issues tabs if they don't want to.

Finally, if we do incorporate these changes I would propose that we change the repo's name to `cdp-roadmap` as I think it's more clear and concise wording for what this repo will contain.

**Comment by hawkticehurst** [comment]
cc @JacksonMaxfield @sarahjliu

**Comment by JacksonMaxfield** [comment]
That was the original goal! But I never spent the energy to write all of my ideas down :sweat_smile: 

I further this proposal by simply saying "lets make a new repo called `cdp-roadmap` instead of changing the name. This is labeled as a fork and uhhh... i guess thats true but its just a fork of an issue template :joy:

**Comment by hawkticehurst** [comment]
Haha oh sweet, got it! Well, I'll just off and create a new repo now in that case modeled after what GitHub is doing.

**Comment by JacksonMaxfield** [comment]
All issues that matter have been transferred. Unless you have an argument against it, I will be deleting this repository in the morning.
